//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretariaControl.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compromisso
    {
        public Compromisso()
        {
            this.ContatoCompromisso = new HashSet<ContatoCompromisso>();
        }
    
        public int IdCompromisso { get; set; }
        public string Descricao { get; set; }
        public string Local { get; set; }
        public System.DateTime DataCompromisso { get; set; }
        public int IdGerente { get; set; }
    
        public virtual ICollection<ContatoCompromisso> ContatoCompromisso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
