//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretariaControl.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecretariaControlEntities : DbContext
    {
        public SecretariaControlEntities()
            : base("name=SecretariaControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public DbSet<Compromisso> Compromisso { get; set; }
        public DbSet<Contato> Contato { get; set; }
        public DbSet<ContatoCompromisso> ContatoCompromisso { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
