//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretariaControl.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Compromisso = new HashSet<Compromisso>();
            this.Contato = new HashSet<Contato>();
        }
    
        public int IdUsuario { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public int Perfil { get; set; }
        public string Foto { get; set; }
        public Nullable<int> IdSecretaria { get; set; }
    
        public virtual ICollection<Compromisso> Compromisso { get; set; }
        public virtual ICollection<Contato> Contato { get; set; }
    }
}
